#!/bin/bash

if [ `hostname` = 'yamato' ] && grep -q ' home$' /etc/resolv.conf; then
    until ssh -t iscandar $'$SHELL -lc \'/usr/bin/ncmpcpp ' "$@" $'\''; do sleep 5 ; done
else
    /usr/bin/ncmpcpp $@
fi

